# TOML config file for virtual clinic

gvc_id = "ffa-citz-iyw" # On  drguruclinicx@gmail.com calendar.
#gvc_id = "wga-woyf-zef" # Test GVC ID.
gvc_more_options_sel = "#yDmH0d > c-wiz > div > div > div.TKU8Od > div.crqnQb > div > div:nth-child(8) > div > div > div.Tmb7Fd > div > div.UvDM0e > div.tB5Jxf-xl07Ob-XxIAqe-OWXEXe-oYxtQd > div:nth-child(1) > span > button" # Out div selector of more options burger menu.
chrome_user_dir = "/home/drguru/chrome/"
chrome_bin = "/usr/bin/google-chrome"
otocam_num = 2 # Camera listed on GVC camera dropdown.
webcam_num = 1 # Camera listed on GVC camera dropdown.
printer_dev = "/dev/usb/lp0" # Printer device.
otocam_dev = "/dev/otocam" # OtoCam device.
check_url = "http://clients4.google.com/generate_204" # URL for checking internet.
browser_window_state = "maximized" # Browser window state.
whatsapp_recipient_suffix = "@s.whatsapp.net" # suffix for whatsapp destination. eg 15554441234@@s.whatsapp.net

# Network/Port Reverse port forward details.
[tunnel.rpc]
    local_port = 2311
    remote_port = 52311
    local_host = ""
    remote_host = "drguruswamyclinic.hyperlinkhome.com"
    user = "drguru"

[tunnel.ssh] 
    local_port = 22
    remote_port = 52222
    local_host = "127.0.0.1"
    remote_host = "drguruswamyclinic.hyperlinkhome.com"
    user = "drguru"

[tunnel.rdp]
    local_port = 3389
    remote_port = 53389
    local_host = "127.0.0.1"
    remote_host = "drguruswamyclinic.hyperlinkhome.com"
    user = "drguru"
