# TOML config file for virtual clinic

gvc_id = "pym-jphe-rwg"
gvc_join_now_selector = "#yDmH0d > c-wiz > div > div > div.TKU8Od > div.crqnQb > div > div.gAGjv > div.vgJExf > div > div > div.d7iDfe.NONs6c > div.shTJQe > div.jtn8y > div.XCoPyb"  # Element selector for GVC join button.
gvc_options_xpath = "//*[@id=\"yDmH0d\"]/c-wiz/div/div/div[34]/div[4]/div[10]/div/div/div[2]/div/div[7]/div[4]/div[1]/span/button" #xPATH for the GVC options burger menu.
chrome_user_dir = "/home/drguru/.config/google-chrome/"
chrome_bin = "/usr/bin/google-chrome"
otocam_num = 2 # Camera listed on GVC camera dropdown.
webcam_num = 1 # Camera listed on GVC camera dropdown.
printer_dev = "/dev/escprint" # Printer device.
otocam_dev = "/dev/otocam" # OtoCam device.
check_url = "http://clients4.google.com/generate_204" # URL for checking internet.
browser_window_state = "maximized" # Browser window state.
whatsapp_recipient_suffix = "@s.whatsapp.net" # suffix for whatsapp destination. eg 15554441234@@s.whatsapp.net

# Network/Port Reverse port forward details.
[tunnel.rpc]
    local_port = 2311
    remote_port = 52311
    local_host = ""
    remote_host = "drguruswamyclinic.hyperlinkhome.com"
    user = "drguru"

[tunnel.ssh] 
    local_port = 22
    remote_port = 52222
    local_host = "127.0.0.1"
    remote_host = "drguruswamyclinic.hyperlinkhome.com"
    user = "drguru"

[tunnel.rdp]
    local_port = 3389
    remote_port = 53389
    local_host = "127.0.0.1"
    remote_host = "drguruswamyclinic.hyperlinkhome.com"
    user = "drguru"
